# Generated by Django 5.2.14 on 2026-08-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_distribucion_utilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmovement',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='semana',
        ),
    ]
