# Generated by Django 5.2.14 on 2026-08-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Administrativo'), ('asesor', 'Asesor'), ('abogada', 'Abogada'), ('finanzas', 'Finanzas')], default='asesor', max_length=20, verbose_name='Rol'),
        ),
    ]
