# Generated by Django 5.2.14 on 2026-08-08 01:40

import secrets

from django.db import migrations, models


def _poblar_tokens(apps, schema_editor):
    """Genera un token único para los perfiles existentes (evita UNIQUE conflict)."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    usados = set()
    for perfil in UserProfile.objects.all():
        if perfil.api_token and perfil.api_token not in usados:
            usados.add(perfil.api_token)
            continue
        token = secrets.token_urlsafe(32)
        while token in usados:
            token = secrets.token_urlsafe(32)
        perfil.api_token = token
        usados.add(token)
        perfil.save(update_fields=['api_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, help_text='Token personal para que la extensión de Chrome se comunique con la app', max_length=64, verbose_name='Token API (extensión Chrome)'),
        ),
        migrations.RunPython(_poblar_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, help_text='Token personal para que la extensión de Chrome se comunique con la app', max_length=64, unique=True, verbose_name='Token API (extensión Chrome)'),
        ),
    ]
