# Generated by Django 5.2.14 on 2026-07-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0017_calculolaboral_conceptos'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculolaboral',
            name='dias_vacaciones_override',
            field=models.PositiveIntegerField(blank=True, help_text='Si el caso no corresponde al total por antigüedad (ej. ya se pagaron o disfrutaron algunos años), captura aquí los días realmente adeudados. Vacío = usa la tabla LFT.', null=True, verbose_name='Días de vacaciones a pagar (manual)'),
        ),
    ]
