# Generated by Django 5.2.14 on 2026-08-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0018_calculolaboral_dias_vacaciones_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='curp',
            field=models.CharField(blank=True, help_text='Opcional al importar citas CLT; se captura después', max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='oficina',
            field=models.CharField(choices=[('plaza_patria', 'Plaza Patria'), ('plaza_patria_abajo', 'Plaza Patria Abajo'), ('otay', 'Otay'), ('cjl', 'CJL (Centro de Justicia Laboral)')], help_text='¿Cuál oficina atendió al cliente?', max_length=30, verbose_name='Oficina que atendió'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
