# Generated by Django 5.2.14 on 2026-08-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0019_alter_cliente_curp_alter_cliente_oficina_and_more'),
    ]

def _renombrar_cjl_a_clt(apps, schema_editor):
    """CJL (Centro de Justicia Laboral) pasa a llamarse CLT conservando sus casos."""
    Cliente = apps.get_model('expedientes', 'Cliente')
    Cliente.objects.filter(oficina='cjl').update(oficina='clt')


def _revertir_clt_a_cjl(apps, schema_editor):
    Cliente = apps.get_model('expedientes', 'Cliente')
    Cliente.objects.filter(oficina='clt').update(oficina='cjl')


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0019_alter_cliente_curp_alter_cliente_oficina_and_more'),
    ]

    operations = [
        migrations.RunPython(_renombrar_cjl_a_clt, _revertir_clt_a_cjl),
        migrations.AlterField(
            model_name='cliente',
            name='oficina',
            field=models.CharField(choices=[('plaza_patria', 'Plaza Patria'), ('otay', 'Otay'), ('clt', 'CLT')], help_text='¿Cuál oficina atendió al cliente?', max_length=30, verbose_name='Oficina que atendió'),
        ),
    ]
