# Generated by Django 5.2.14 on 2026-08-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0020_alter_cliente_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre normalizado (mayúsculas, sin acentos)', max_length=200, unique=True, verbose_name='Empresa')),
                ('domicilio', models.TextField(blank=True, help_text='Domicilio completo tal como viene en el archivo', verbose_name='Domicilio')),
                ('abogado', models.CharField(blank=True, help_text='Abogado/representante de la empresa (opcional)', max_length=200, verbose_name='Abogado')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('tipo_persona', models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], default='moral', help_text='Detectado automáticamente al importar', max_length=10, verbose_name='Tipo de persona')),
                ('domicilio_calle', models.CharField(blank=True, max_length=200, verbose_name='Calle (domicilio)')),
                ('domicilio_numero', models.CharField(blank=True, max_length=20, verbose_name='Número (domicilio)')),
                ('domicilio_colonia', models.CharField(blank=True, max_length=200, verbose_name='Colonia (domicilio)')),
                ('domicilio_cp', models.CharField(blank=True, max_length=10, verbose_name='Código Postal (domicilio)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa (catálogo)',
                'verbose_name_plural': 'Empresas y Domicilios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='expedientes_nombre_ef7800_idx')],
            },
        ),
    ]
