# Generated by Django 5.2.14 on 2026-08-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0021_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaconciliacion',
            name='modo',
            field=models.CharField(choices=[('automatico', 'Automático (Headless)'), ('debug', 'Visible (Debug)'), ('extension', 'Extensión de Chrome')], default='automatico', max_length=15, verbose_name='Modo'),
        ),
    ]
