# Generated by Django 5.2.14 on 2026-08-08 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0022_alter_tareaconciliacion_modo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='leido_por',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que ya marcaron el aviso como leído/entendido', related_name='avisos_leidos', to=settings.AUTH_USER_MODEL, verbose_name='Leído por'),
        ),
    ]
