# Generated by Django 5.2.14 on 2026-08-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0023_aviso_leido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Opcional. Si se define, el aviso deja de mostrarse automáticamente a partir de esta fecha.', null=True, verbose_name='Vence'),
        ),
    ]
