# Generated by Django 5.2.14 on 2026-08-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0025_cliente_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa_curp',
            field=models.CharField(blank=True, help_text='Solo aplica si el patrón es persona física', max_length=18, verbose_name='CURP del patrón (persona física)'),
        ),
    ]
