# Generated by Django 5.2.14 on 2026-08-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0026_add_empresa_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa_rfc',
            field=models.CharField(blank=True, help_text='RFC de la empresa/patrón (no confundir con el RFC del trabajador)', max_length=13, verbose_name='RFC del patrón'),
        ),
    ]
