# Generated by Django 5.2.14 on 2026-08-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0027_add_empresa_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_despido',
            field=models.CharField(blank=True, choices=[('justificado', 'Despido justificado'), ('injustificado', 'Despido injustificado'), ('voluntario', 'Renuncia voluntaria'), ('rescision', 'Rescisión'), ('otro', 'Otro')], help_text='Tipo de despido: justificado, injustificado, renuncia voluntaria, rescisión u otro', max_length=20, verbose_name='Tipo de despido'),
        ),
    ]
