# Generated by Django 6.0.4 on 2026-08-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0028_add_tipo_despido_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='comprobante_convenio',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante que indica fecha y monto del convenio', null=True, upload_to='comprobantes/', verbose_name='Comprobante de convenio'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Imagen del comprobante de pago enviado al admin de conciliación', null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago'),
        ),
    ]
