# Generated by Django 5.2.14 on 2026-10-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0029_add_comprobante_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='circunstancias_despido',
            field=models.TextField(blank=True, help_text='Cómo ocurrió el despido: lo que te dijeron, cómo te notificaron, etc.', verbose_name='Circunstancias del despido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documentos_prueba',
            field=models.TextField(blank=True, help_text='Documentos que tiene el cliente: contratos, recibos, mensajes, cartas, etc. (uno por línea si son varios)', verbose_name='Documentos disponibles (prueba documental)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='testigos',
            field=models.TextField(blank=True, help_text='Nombres y datos de personas que pueden corroborar los hechos (una por línea si son varios)', verbose_name='Testigos de los hechos'),
        ),
    ]
