# Generated by Django 5.2.14 on 2026-10-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0030_cliente_circunstancias_despido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculolaboral',
            name='descanso_semanal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Días de descanso semanal laborados'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='dias_descanso_semanal_cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Días de descanso semanal en que se laboró sin pago (art. 73 LFT)', verbose_name='Días de descanso semanal laborados'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='horas_extra_excedentes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Horas que exceden el límite del art. 66 LFT (máx. 4 h/semana): se pagan al triple', max_digits=8, null=True, verbose_name='Horas extra excedentes (art. 68)'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='horas_extra_normales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Horas dentro del límite semanal del art. 66 LFT (9 h/semana en 2026): se pagan al doble', max_digits=8, null=True, verbose_name='Horas extra al doble (art. 66)'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='incluir_descanso_semanal',
            field=models.BooleanField(default=False, verbose_name='Incluir días de descanso semanal'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='salario_diario_integrado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base de las indemnizaciones (arts. 84 y 89 LFT): cuota diaria y parte proporcional de las prestaciones que integran el salario', max_digits=12, verbose_name='Salario diario integrado'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='salario_integrado_ayudas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ayuda de transporte, despensa, vivienda, etc. (art. 84 LFT)', max_digits=10, verbose_name='Ayudas yoluciones'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='salario_integrado_cuota_diaria',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parte de la cuota diaria que absorbe el patrón (art. 84 LFT)', max_digits=10, verbose_name='Cuota diaria (IMSS)'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='salario_integrado_gratificaciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bonos, comisiones, gratificaciones equivalentes (art. 84 LFT)', max_digits=10, verbose_name='Gratificaciones y bonos'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='salario_integrado_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alternativa al desglose: porcentaje sobre el salario diario. 0 = usar el desglose', max_digits=6, verbose_name='% de prestaciones integradas'),
        ),
        migrations.AddField(
            model_name='calculolaboral',
            name='zona_salarial',
            field=models.CharField(default='frontera', help_text='Zona Libre de la Frontera Norte o resto del país', max_length=12, verbose_name='Zona salarial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona_salarial',
            field=models.CharField(choices=[('frontera', 'Zona Libre de la Frontera Norte'), ('general', 'Resto del país')], default='frontera', help_text='Zona Libre de la Frontera Norte (Tijuana, Mexicali, Ciudad Juárez…) o resto del país. Define el salario mínimo y el tope de los arts. 485/486 LFT.', max_length=12, verbose_name='Zona salarial'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='indemnizacion_20dias_dias_por_ano',
            field=models.PositiveIntegerField(default=20, help_text='20 días por año de servicios (art. 50 fr. II LFT)', verbose_name='Días por año (indemnización 20 días)'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='prima_antiguedad_anios_voluntaria',
            field=models.PositiveIntegerField(default=15, help_text='El art. 162 fr. III LFT sólo paga prima de antigüedad en la renuncia voluntaria a partir de 15 años de servicios', verbose_name='Años para prima antigüedad en renuncia'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='salario_integrado_modo',
            field=models.CharField(choices=[('explicit', 'Por conceptos (cuota diaria, gratificaciones, ayudas…)'), ('porcentaje', 'Por porcentaje sobre el salario diario')], default='explicit', help_text='Base de las indemnizaciones: cuota diaria y parte proporcional de las prestaciones del art. 84 LFT.', max_length=15, verbose_name='Modo de salario integrado'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='salario_integrado_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sólo si el modo es "Por porcentaje"', max_digits=6, verbose_name='% prestaciones integradas'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='vacaciones_antes_de_un_ano',
            field=models.CharField(choices=[('proporcional', 'Proporcional (12 × tiempo/año)'), ('ninguna', 'Ninguna (el art. 76 LFT exige más de un año de servicios)')], default='proporcional', help_text='Criterio aplicable cuando la relación termina antes del primer aniversario. El criterio mayoritario es "ninguna".', max_length=15, verbose_name='Vacaciones con menos de un año'),
        ),
        migrations.AlterField(
            model_name='calculolaboral',
            name='dias_festivos_cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Días de descanso obligatorio laborados y no pagados (arts. 74 y 75 LFT)', verbose_name='Cantidad de días festivos'),
        ),
        migrations.AlterField(
            model_name='calculolaboral',
            name='dias_vacaciones_vencidos',
            field=models.PositiveIntegerField(default=0, help_text='Días de vacaciones de ciclos ANTERIORES al último año cumplido que no se pagaron. El último año cumplido ya se incluye en el cálculo automático de vacaciones, así que aquí sólo van los años adicionales', verbose_name='Días de vacaciones de ciclos anteriores'),
        ),
        migrations.AlterField(
            model_name='calculolaboral',
            name='horas_extra_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Número total de horas extra trabajadas. Si no captura el desglose, el motor las reparte contra los topes semanales del año (9 h al doble en 2026, más 4 h al triple)', max_digits=8, verbose_name='Cantidad de horas extra'),
        ),
        migrations.AlterField(
            model_name='calculolaboral',
            name='vacaciones_vencidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacaciones de ciclos anteriores'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='aguinaldo_dias',
            field=models.PositiveIntegerField(default=15, help_text='Mínimo legal: 15 días (art. 87 LFT)', verbose_name='Días de aguinaldo'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='indemnizacion_dias',
            field=models.PositiveIntegerField(default=90, help_text='3 meses = 90 días (art. 50 fr. III LFT)', verbose_name='Días de indemnización'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='nombre',
            field=models.CharField(default='Configuración Legal 2026', max_length=100, verbose_name='Nombre de la configuración'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='prima_antiguedad_dias_por_ano',
            field=models.PositiveIntegerField(default=12, help_text='12 días por año (art. 162 fr. I LFT)', verbose_name='Días por año(prima antigüedad)'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='prima_vacacional_porcentaje',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Mínimo 25% (art. 80 LFT)', max_digits=5, verbose_name='% Prima vacacional'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='salario_minimo',
            field=models.DecimalField(decimal_places=2, default=315.04, help_text='Salario mínimo general diario (2026: $315.04)', max_digits=10, verbose_name='Salario mínimo general'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='salario_minimo_frontera',
            field=models.DecimalField(decimal_places=2, default=440.87, help_text='Salario mínimo ZLFN (2026: $440.87)', max_digits=10, verbose_name='Salario mínimo frontera'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='tope_prima_multiplo',
            field=models.PositiveIntegerField(default=2, help_text='Normalmente 2 (doble del salario mínimo del área)', verbose_name='Múltiplo del tope'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='tope_prima_tipo',
            field=models.CharField(choices=[('uma', '2 × UMA (referencia, NO es el tope legal)'), ('salario_minimo', '2 × Salario Mínimo general'), ('salario_minimo_frontera', '2 × Salario Mínimo Frontera Norte')], default='salario_minimo_frontera', help_text='Tope salarial para prima de antigüedad. El valor legal es el doble del salario mínimo del área (arts. 485/486 LFT).', max_length=30, verbose_name='Tipo de tope'),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='uma_diaria',
            field=models.DecimalField(decimal_places=2, default=117.31, help_text='Valor de la UMA diaria (2026: $117.31, vigente desde el 1 de febrero)', max_digits=10, verbose_name='UMA diaria'),
        ),
    ]
