# Generated by Django 5.2.14 on 2026-10-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0032_legalconfig_valores_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalconfig',
            name='prima_antiguedad_dias_por_ano',
            field=models.PositiveIntegerField(default=12, help_text='12 días por año (art. 162 fr. I LFT)', verbose_name='Días por año (prima antigüedad)'),
        ),
    ]
