# Generated by Django 5.2.14 on 2026-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0033_alter_legalconfig_prima_antiguedad_dias_por_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accion_preferida',
            field=models.CharField(choices=[('indemnizacion', 'Indemnización (3 meses de salario integrado)'), ('reinstalacion', 'Reinstalación en el puesto que desempeñaba')], default='indemnizacion', help_text='Elección del trabajador conforme al art. 48 LFT. Si procede la reinstalación, la indemnización de 3 meses no se incluye en el total.', max_length=15, verbose_name='Acción preferida'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='despido_comunicado_por',
            field=models.CharField(blank=True, help_text='Nombre de quien le comunicó la separación (jefe, supervisor, RR.HH.)', max_length=150, verbose_name='Quién comunicó la separación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='despido_documento_motivo',
            field=models.CharField(blank=True, help_text='Causa que el documento de terminación consigna (si lo hubo)', max_length=300, verbose_name='Motivo señalado en el documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='despido_frase',
            field=models.TextField(blank=True, help_text='Frase textual manifestada al separarlo.', verbose_name='Qué le dijeron al separarlo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='despido_lugar',
            field=models.CharField(blank=True, help_text='Oficina, caseta, planta o lugar físico donde ocurrió', max_length=200, verbose_name='Dónde ocurrió la separación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='despido_otra_modalidad',
            field=models.TextField(blank=True, help_text='Describa la modalidad cuando no sea verbal, documento ni negada la entrada', verbose_name='Otra modalidad: explicación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hubo_documento_despido',
            field=models.BooleanField(default=False, help_text='Si no se entregó aviso escrito, el art. 47 LFT presume la separación injustificada aunque el patrón alegue una causa.', verbose_name='Se entregó documento de terminación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lugar_trabajo',
            field=models.CharField(blank=True, help_text='Nombre o dirección del centro de trabajo donde prestaba servicios', max_length=200, verbose_name='Centro de trabajo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='modalidad_despido',
            field=models.CharField(blank=True, choices=[('verbal', 'Despido verbal (sin documento)'), ('escrito', 'Despido notificado por documento'), ('acceso', 'Se le impidió el acceso al centro de trabajo'), ('otro', 'Otra modalidad')], help_text='Cómo se le comunicó la separación: verbal, documento, negada la entrada u otra modalidad. Define el redactado de los HECHOS.', max_length=12, verbose_name='Modalidad del despido'),
        ),
        migrations.AlterField(
            model_name='calculolaboral',
            name='salario_integrado_ayudas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ayuda de transporte, despensa, vivienda, etc. (art. 84 LFT)', max_digits=10, verbose_name='Ayudas y prestaciones'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='circunstancias_despido',
            field=models.TextField(blank=True, help_text='Anotaciones adicionales del asesor. Se suman al redactado estructurado como último hecho de la demanda.', verbose_name='Circunstancias del despido (texto libre)'),
        ),
    ]
