# Generated by Django 5.2.14 on 2026-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0034_cliente_accion_preferida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculolaboral',
            name='requiere_revision',
            field=models.BooleanField(default=False, verbose_name='Revisar prestaciones tras cambios de datos'),
        ),
    ]
