# Generated by Django 5.2.14 on 2026-10-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0035_calculo_requiere_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='oficina',
            field=models.CharField(blank=True, choices=[('plaza_patria', 'Plaza Patria'), ('otay', 'Otay'), ('clt', 'CLT')], help_text='¿Cuál oficina atendió al cliente? Opcional: si no se sabe aún, se puede dejar vacío y completar después.', max_length=30, verbose_name='Oficina que atendió'),
        ),
    ]