# Generated by Django 5.2.14 on 2026-10-08 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0036_alter_cliente_oficina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='asesor',
            field=models.ForeignKey(limit_choices_to={'profile__rol__in': ['asesor', 'abogada']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Asesor asignado'),
        ),
    ]
