# Generated by Django 5.2.14 on 2026-10-09 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0037_alter_expediente_asesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imss_confirmado',
            field=models.BooleanField(default=False, verbose_name='Información de IMSS confirmada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imss_documento',
            field=models.CharField(blank=True, max_length=300, verbose_name='Documento o fuente del registro IMSS'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imss_salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario diario registrado ante el IMSS'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imss_salario_inferior',
            field=models.BooleanField(default=False, verbose_name='¿Fue registrado con un salario inferior al real?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tuvo_imss',
            field=models.BooleanField(default=False, verbose_name='¿Estuvo dado de alta en el IMSS?'),
        ),
        migrations.CreateModel(
            name='HojaPrestaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(default=dict)),
                ('resultado', models.JSONField(default=dict)),
                ('huella', models.CharField(blank=True, max_length=64)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_prestaciones', to='expedientes.expediente')),
            ],
        ),
    ]
